image: node:6

before_script:
    - apt-get -qq update
    - apt-get -qq install -y python2.7 python2.7-dev build-essential make gcc g++ libicu-dev
    - npm set progress=false
    - npm install --silent

pages:
  script:
    - npm run build
  artifacts:
    paths:
      - dist
